# Generated by Django 3.2.1 on 2021-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка на камеру')),
                ('date', models.DateTimeField(verbose_name='Дата срабатывания')),
                ('detected_link', models.ImageField(upload_to='', verbose_name='Cрабатывание')),
            ],
            options={
                'verbose_name': 'Обнаружение',
                'verbose_name_plural': 'Обнаружения',
            },
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка на камеру')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
    ]
