# Generated by Django 3.2.1 on 2021-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата срабатывания'),
        ),
    ]
