# Generated by Django 3.2.1 on 2021-06-05 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0002_alter_detections_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата срабатывания'),
        ),
    ]
