# Generated by Django 3.2.1 on 2021-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0004_remove_detections_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='detected_link',
            field=models.ImageField(upload_to='datections', verbose_name='Cрабатывание'),
        ),
    ]
