# Generated by Django 3.2.1 on 2021-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0006_alter_detections_detected_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detections',
            old_name='detected_link',
            new_name='detected_frame',
        ),
        migrations.RemoveField(
            model_name='detections',
            name='link',
        ),
        migrations.AddField(
            model_name='detections',
            name='cam_link',
            field=models.TextField(default='NULL', verbose_name='Ссылка на камеру'),
        ),
        migrations.AddField(
            model_name='detections',
            name='cam_name',
            field=models.TextField(default='NULL', verbose_name='Название камеры'),
        ),
    ]
